### ISSUE TITLE
Store 목록 API(/api/v1/store API) 생성

### ISSUE THREAD

**Issue by devchanki** [FC-InnerCircle/icd01-team01-o2o1-be#2]
## ✍🏻 Description

레이어드 아키텍쳐로 Store 목록 조회(/api/v1/store API) API 생성.

## ✅ To-Do

- [x] clean architecture 기반의 폴더 및 파일 구성(application, domain, infrastructure...)
- [x] Store 도메인 정의
- [x] Store 정보를 연동할 Infrastructure 내 mock 데이터 형태로 연동 가정 후  /api/v1/store API 구현

## 📨 ETC

아키텍쳐는 다음과 같은 구조로 구성 예정

```
// Domain Layer
presentation
 api
   - XxxController
   - XxxDto
 dto
   - XxxRequest
   - XxxResponse
application
 - XxxService
	 
domain
   - 도메인 객체
   - XxxReader, XxxStore, XxxService
   - XxxCommand, XxxInfo
infrastructure
  client
    - XxxOutPort (interface)
    - XxxApiClient (impl)
  repository
    - XxxRepository
```
적용할 아키텍쳐 강의 → https://skillflo.io/course/10108

**Comment by devchanki** [comment]
조회 시 Pagenation 조건 등이 있는데 2팀 조회 시에도 필요하고, 우리팀 프론트에서도 응답값으로 필요한데 
해당 응답 등은 Domain Layer 에서 관리하는 데이터가 아닐 것 같아 보이는데 어떻게 구현해야 할지 어려움을 겪는 중입니다
그냥 서비스 단에서..처리 해야 할지..
