### ISSUE TITLE
Store 상세 조회(/api/v1/store API) API

### ISSUE THREAD

**Issue by devchanki** [FC-InnerCircle/icd01-team01-o2o1-be#3]
## ✍🏻 Description

Store 상세 조회(/api/v1/store API) API 생성.

## ✅ To-Do

- [x] clean architecture 기반의 폴더 및 파일 구성(application, domain, infrastructure...)
- [x] Store 도메인 정의
- [x] Store 정보를 연동할 Infrastructure 내 mock 데이터 형태로 연동 가정 후  /api/v1/store/${storeId} API 틀 구현 / 메뉴, 예외처리, 공용화 된 ApiReturn 등은 추후 구현 예정 

## 📨 ETC

메뉴는 현재 미 구현. 

아키텍쳐는 다음과 같은 구조로 구성 예정

![image](https://github.com/user-attachments/assets/039534ac-68d3-49c9-ab0b-ee69cdaa36b4)
